[theme]
base            = "light"
primaryColor    = "#0068C9"
font            = "sans serif"

[server]
port            = 8501
headless        = true
address         = "0.0.0.0"

[browser]
gatherUsageStats = false
